export const FAQ_ADD_CATEGORY = 'FAQ_ADD_CATEGORY'
export const FAQ_ADD_CATEGORIES = 'FAQ_ADD_CATEGORIES'
export const FAQ_ADD_QUESTION = 'FAQ_ADD_QUESTION'
export const FAQ_ADD_QUESTIONS = 'FAQ_ADD_QUESTIONS'
